name: Build

on:
  workflow_call:
    inputs:
      publish_artifacts:
        description: "Publish workflow artifacts"
        type: boolean
        default: false

jobs:
  shifty-build:
    name: Build webapp
    uses: ./.github/workflows/shifty-build.yml
    with:
      publish_artifacts: ${{ inputs.publish_artifacts }}
    secrets: inherit

  infra-build:
    name: Build infrastructure
    uses: ./.github/workflows/infra-build.yml
    secrets: inherit
