name: Build

on:
  workflow_call:
    inputs:
      publish_artifacts:
        description: "Publish workflow artifacts"
        type: boolean
        default: false
      settings_file:
        description: "The filename of the appsettings file"
        type: string

jobs:
  shifty-build:
    name: Build webapp
    uses: ./.github/workflows/shifty-build.yml
    with:
      publish_artifacts: ${{ inputs.publish_artifacts }}
      settings_file: ${{ inputs.settings_file }}
    secrets: inherit

  infra-build:
    name: Build infrastructure
    uses: ./.github/workflows/infra-build.yml
    secrets: inherit
