name: Deploy Webapp

on:
  push:
    branches: [develop, production]

jobs:
  shifty-build:
    uses: ./.github/workflows/shifty-build.yml
    with:
      publish_artifacts: true
    secrets: inherit

  infra-build:
    name: Build infrastructure
    uses: ./.github/workflows/infra-build.yml
    secrets: inherit

  deploy_dev:
    name: Deploy dev
    if: github.ref_name == 'develop'
    needs: [shifty-build, infra-build]
    uses: ./.github/workflows/template-deploy.yml
    secrets: inherit
    with:
      environment: dev
      subscriptionId: analogio-dev

  deploy_prod:
    name: Deploy prd
    if: github.ref_name == 'production'
    needs: [shifty-build, infra-build]
    uses: ./.github/workflows/template-deploy.yml
    secrets: inherit
    with:
      environment: prd
      subscriptionId: analogio-prd

  # deploy:
  #   name: Deploy Webapp
  #   runs-on: ubuntu-latest
  #   needs: [buildtest]
  #   environment:
  #     name: dev
  #     url: ${{ vars.AZURE_STAPP_URL }}

  #   steps:
  #     - name: Download Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: shifty
  #     - name: Deploy to Azure Web App
  #       id: webapp-deploy
  #       uses: Azure/static-web-apps-deploy@v1
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         action: "upload"
  #         app_location: "."
  #         api_location: ""
  #         output_location: ""
  #         skip_app_build: true
  #         skip_api_build: true
