name: Deploy to dev

on:
  push:
    branches:
      - main

jobs:
  dev-deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: dev
      settings_file: "dev.appsettings.json"
