name: Deployment of Webapp

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: "Target Environment. Can either be 'dev' or 'prd'"
      settings_file:
        type: string
        required: true
        description: "The filename of the appsettings file to use"

jobs:
  build-all:
    name: Build codebase
    uses: ./.github/workflows/build.yml
    with:
      publish_artifacts: true
      settings_file: ${{ inputs.settings_file }}
    secrets: inherit

  deploy:
    needs: [build-all]
    name: Azure Deployment
    runs-on: ubuntu-22.04
    environment:
      name: ${{ inputs.environment }}
      url: ${{ vars.AZURE_STAPP_URL }}
    concurrency:
      group: ${{ inputs.environment }}
      cancel-in-progress: false

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: arm

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          scope: subscription
          region: "West Europe"
          template: azuredeploy.json
          parameters: "environment=${{ inputs.environment }}"
          deploymentName: "azuredeploy-${{github.run_number}}"
          failOnStdErr: true

      - name: Download Shifty Artifact
        uses: actions/download-artifact@v3
        with:
          name: shifty

      - name: Deploy to Azure Web App
        id: webapp-deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "."
          api_location: ""
          output_location: ""
          skip_app_build: true
          skip_api_build: true
