name: Deploy Webapp

on:
  push:
    branches: [develop, production]

jobs:
  shifty-build:
    uses: ./.github/workflows/shifty-build.yml
    with:
      publish_artifacts: true
    secrets: inherit

  infra-build:
    name: Build infrastructure
    uses: ./.github/workflows/infra-build.yml
    secrets: inherit

  deploy_dev:
    name: Deploy dev
    if: github.ref_name == 'develop'
    needs: [shifty-build, infra-build]
    uses: ./.github/workflows/template-deploy.yml
    secrets: inherit
    with:
      environment: dev
      subscriptionId: analogio-dev

  deploy_prod:
    name: Deploy prd
    if: github.ref_name == 'production'
    needs: [shifty-build, infra-build]
    uses: ./.github/workflows/template-deploy.yml
    secrets: inherit
    with:
      environment: prd
      subscriptionId: analogio-prd
