name: Build Webapp

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      publish_artifacts:
        description: "Publish workflow artifacts"
        type: boolean
        default: false
      settings_file:
        description: "The filename of the appsettings file"
        type: string

jobs:
  build-test:
    name: Build and test Webapp
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: Restore dependencies
        run: dotnet restore .
      - name: Settings override
        run: mv -f "infrastructure/${{ inputs.settings_file }}" Shifty.App/wwwroot/appsettings.json
      - name: Build Shifty App
        run: dotnet build . --no-restore /p:ContinuousIntegrationBuild=true --configuration Release
      - name: Run tests
        run: dotnet test . --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Publish Shifty App
        run: dotnet publish --no-restore --configuration Release --output publish
      - name: Publish workflow artifact
        if: ${{ inputs.publish_artifacts }}
        uses: actions/upload-artifact@v4
        with:
          name: shifty
          path: publish/wwwroot
          retention-days: 1
          if-no-files-found: error
